modLoader="javafml"  
loaderVersion="[40,)"  
license="MIT License"   
issueTrackerURL=""  
 
[[mods]]  
modId="storymobs"  
version="1.18.2-1.0"  
displayName="Story Mod"  
updateJSONURL=""  
displayURL="https://www.curseforge.com/minecraft/mc-mods/story-mobs"  
logoFile="storymobs_logo.png"  
credits="Vaguely Interesting for the art, GentWorm and nonamecrackers2 for writing the code, Swagboi7 for structure designs and ideas"  
authors="Vaguely Interesting, GentWorm, Swagboi7"  
description='''
This mod adds mobs from Minecraft: Story Mode into the game!
'''  